### ISSUE TITLE
Warnings for undefined $this clause in phtml files

### ISSUE THREAD

**Issue by sparrowek** [pdt-eg/Core-Plugin#100]
There is a warning: "variable $this is undefined" when editing .phtml files – it would be great if it could be ignored.

**Comment by str** [comment]
Variable $this is undefined happens also in Zend Studio 12.5 in all view files.

**Comment by str** [comment]
I think this is fixed. I can do 

```php
<?php 
/**
 * @var MyViewClass $this
 */
```
and it works. I think this is fixed with #104

**Comment by zulus** [comment]
Validator moved to PDT
