### ISSUE TITLE
Variable is undefined occurs too often

### ISSUE THREAD

**Issue by mlocati** [pdt-eg/Core-Plugin#103]
In the following code:

``` PHP
function foo() {
    static $static;
    if(!isset($static)) {
        $static = 1;
    }
    return $static;
}
```

`$static` is marked as undefined in the lines `static $static;` and `if(!isset($static)) {` whereas it shouldn't...

In the following code:

``` PHP
function bar() {
    if(preg_match('/.+/', 'hi', $match)) {
        return $match[0];
    }
}
```

`$match` is marked as undefined, but it shouldn't since it's being defined by `preg_match`...

**Comment by str** [comment]
I come from http://stackoverflow.com/questions/28760996/eclipse-pdt-semantic-analysis looking for a way to define a variable in a docblock with @var

> Reading variable information from comments is still on my todo list

Please +1 for this.

**Comment by str** [comment]
I think this is fixed in #104

**Comment by glen-84** [comment]
I'm also looking for a solution to the issue with "autocreated" variables.

I submitted an issue [here](https://bugs.eclipse.org/bugs/show_bug.cgi?id=529166) by mistake.

I suppose `/** @var $matches array */` could work as a temporary solution.

**Comment by zulus** [comment]
Moved to PDT

**Comment by glen-84** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=532891
