### ISSUE TITLE
Add possibility to specify defined variables

### ISSUE THREAD

**Issue by mlocati** [pdt-eg/Core-Plugin#104]
In PHP we often have cases when we define variables in one file and we use these variables in another file.
It would be fine to be able to specify the defined variables.
For instance, jshint supports this syntax:
```JavaScript
/* global definedVariable1, definedVariable2 */
```

What about adding support for such an approach?
I'm thinking about something like these lines to be placed at the beginning of the file:

```PHP
/* @var $definedVariable1 \DateTime */
/* @var $definedVariable1 array */
```

**Comment by Fedik** [comment]
:+1: 

for 
```
/**
 * @var string $var1 
 * @var array $var2
 * @var DateTime $var3
 */
```
similar as in method descriptions

**Comment by Fedik** [comment]
@zulus thanks for fix :beer:

**Comment by str** [comment]
Does this solve #100 and #103 ?

**Comment by str** [comment]
Defining arrays is still not yet working as described in https://www.phpdoc.org/docs/latest/guides/types.html#arrays

```php
 /**
  * @var string   $thisWorks
  * @var string[] $thisDoesNotWork
  */
