### ISSUE TITLE
incorrect warning if interface is implemented in extended class

### ISSUE THREAD

**Issue by thkoch2001** [pdt-eg/Core-Plugin#107]
Create three php files A.php, B.php, C.php and put these classes and interfaces in the correct files:

``` php
<?php
class A extends B implements C {
}

abstract class B {
    public function f(){}
}

interface C {
    public function f();
}
```

I get a warning on class A:

```
The class A must implement the inherited abstract method f  A.php   /PDTTest    line 3  PHP Semantic analysis
```

You might need to clean and rebuild the project to trigger the warning. I can not reproduce the warning if all three types are defined in the same file.

I think the warning should not be there since A inherits the implementation from B although B did not know about the interface.

I've not tested whether the same warning is also triggered if the implementation is inherited from a trait.

**Comment by zulus** [comment]
Support dropped. It's part of PDT 5.0
