### ISSUE TITLE
Disable or drop pex refactoring support with PDT 3.4

### ISSUE THREAD

**Issue by zulus** [pdt-eg/Core-Plugin#114]
There are pending patch from Zend with Studio refactoring support [1]. After merge we should disable/drop current implementation for PDT 3.4.

[1] - https://git.eclipse.org/r/#/c/39463
[2] - https://bugs.eclipse.org/bugs/show_bug.cgi?id=149818

**Comment by iteman** [comment]
@zulus OK, I would work for it.

**Comment by zulus** [comment]
Since now, PDT build have own refactoring support ;)

**Comment by zulus** [comment]
fixed by #114
