### ISSUE TITLE
Semantic Validation probably blocks main build process

### ISSUE THREAD

**Issue by mniewrzal** [pdt-eg/Core-Plugin#115]
I noticed strange behavior when semantic validation is enabled. It looks that when build participant is waiting for DLTK indexing to finish it is blocking ParserBuildParticipant from PDT. It is clearly visible during build after importing big project. I did something like this:
- Import larger project e.g. magento2
- Look into Progress view, "Building workspace" task will be showing just one file until indexing will be finished

I looked briefly at code and probably when first file is processed then method "ModelManager.getModelManager().getIndexManager().waitUntilReady()" is blocking whole process.

**Comment by zulus** [comment]
You have right. Usage and Implement validators are based on dltk index so we waiting until index finish, to avoid false positives. I'm still thinking about best solution for this problem.

**Comment by mniewrzal** [comment]
Good to know you are aware of that:) Look at "org.eclipse.dltk.core.builder.IScriptBuilder" (I think it is triggered after main build) or you can also move validation to WST (like Symfony plugin if I remember correctly).

**Comment by zulus** [comment]
I moved it to DLTK because in this way, they work much faster ;)

Besides only from from this place I can report dependencies between files.

**Comment by zulus** [comment]
I hope that after recent changes in doctrine index this issue is less important ;)

**Comment by mniewrzal** [comment]
If it is by design then it is not big issue;) I created this thread to be sure you are aware of that. If you like you can close this issue.

**Comment by zulus** [comment]
Now this problem is part of PDT :P
