### ISSUE TITLE
PHP CodeSniffer directory/file level rules

### ISSUE THREAD

**Issue by eidng8** [pdt-eg/Core-Plugin#118]
We have two directories:

``` text
-+
 +- src
 +- tests
```

Our compile script has applied phpcs as:
- some common standards to the `src` directory;
- same common standards as `src` directory, _plus_ phpunit standard.

However, I can't find a way to do the same thing in eclipse with the pdt-ext tools.

**Comment by zulus** [comment]
PHP Code Sniffer support isn't part of this plugin.
