### ISSUE TITLE
Move a class to a new folder/namespace, update references

### ISSUE THREAD

**Issue by pulse00** [pdt-eg/Core-Plugin#12]
If I have a class under name\space\Class and am going to move it to new\name\space\Class. Can all the references (e.g. all use statements, all \name\space\Class statements and the namespace statement in the class itself) updated, according to the new namespace?

Assuming the project follows psr-0.

(originally reported by @gossi)

**Comment by zulus** [comment]
Refactoring is now part of PDT. Closing.
