### ISSUE TITLE
Cannot bind to an undefined command: plug-in='org.pdtextensions.core.ui', id='org.pdtextensions.core.ui.edit.text.extract.method'

### ISSUE THREAD

**Issue by berturion** [pdt-eg/Core-Plugin#120]
Hello,
I just made a fresh install on Ubuntu 14.04 64bit with those elements:
- Last Eclipse Luna for Java Deveoloppers (https://eclipse.org/downloads/packages/eclipse-ide-java-developers/lunasr2)
- I made immidiatly an update in Eclipse
- I added http://p2-dev.pdt-extensions.org/ update site and installed only PDT (not pdt-extensions)
- Close, reopen eclipse and installed only PDT-Extensions
- Then, each time eclipse is open I have in error logs:

    !ENTRY org.eclipse.ui 2 0 2015-03-08 16:55:45.955
    !MESSAGE Warnings while parsing the key bindings from the 'org.eclipse.ui.commands' extension point
    !SUBENTRY 1 org.eclipse.ui 2 0 2015-03-08 16:55:45.955
    !MESSAGE Cannot bind to an undefined command: plug-in='org.pdtextensions.core.ui', id='org.pdtextensions.core.ui.edit.text.extract.method'

But, apparently, that works. I just wanted you to know that error log.

**Comment by iteman** [comment]
This issue has been fixed by eb1b6cc179f6871636b41865f088307abcb1b73c in the master branch. Thank you! :smile:

**Comment by berturion** [comment]
Your welcome ! Thank YOU for this great plugin :-)

**Comment by Yonn-Trimoreau** [comment]
Still got the problem, but it's not working for me :s

**Comment by zulus** [comment]
Refactoring support was dropped to avoid conflicts with PDT.

Zend move owne solution from Zend Studio into PDT 3.4.0.
