### ISSUE TITLE
Reverse Namespace Resolver

### ISSUE THREAD

**Issue by gossi** [pdt-eg/Core-Plugin#123]
In PDT 3.5 "group by namespaces" works again (maybe even earlier but I just discovered this). When active, selecting a namespace in the PHP Explorer can be resolved to its respective directory and as such prefilled in new Class/Interface Dialog. The namespace resolver schema can be used for that. The Composer plugin can provide the required information.

**Comment by zulus** [comment]
Composer is part of PDT, and should be done on that side.
