### ISSUE TITLE
PHP-CS binding conflict

### ISSUE THREAD

**Issue by zulus** [pdt-eg/Core-Plugin#127]
PHP-CS use cmd+shift+n shortcut to run.

This is standard eclipse inspect shortcut (during debug), and since 3.6 also used by PDT.

**Comment by glen-84** [comment]
Here is the log entry:

    !ENTRY org.eclipse.jface 2 0 2015-10-17 22:43:25.252
    !MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
    !SUBENTRY 1 org.eclipse.jface 2 0 2015-10-17 22:43:25.252
    !MESSAGE A conflict occurred for CTRL+SHIFT+N:
    Binding(CTRL+SHIFT+N,
        ParameterizedCommand(Command(org.eclipse.php.debug.ui.commands.InspectDelegate,Inspect,
            Inspect result of evaluating selected text,
            Category(org.eclipse.debug.ui.category.run,Run/Debug,Run/Debug command category,true),
            org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@4d71476c,
            ,,true),null),
        org.eclipse.ui.defaultAcceleratorConfiguration,
        org.eclipse.php.ui.phpEditorScope,,,system)
    Binding(CTRL+SHIFT+N,
        ParameterizedCommand(Command(org.pdtextensions.core.ui.command.phpcsfixer,Run PHP-CS-Fixer,
            Run PHP-CS-Fixer on files and folders,
            Category(org.eclipse.core.commands.categories.autogenerated,Uncategorized,Commands that were either auto-generated or have no category,true),
            org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@5e1535e0,
            ,,true),null),
        org.eclipse.ui.defaultAcceleratorConfiguration,
        org.eclipse.php.core.phpsource,,,system)

**Comment by zulus** [comment]
Somebody have a proposition which shortcut should be used?

**Comment by glen-84** [comment]
Is there a way to see which key combinations are available?

TBH, I don't even use CS Fixer, so it would nice if it was moved to a separate plug-in.
