### ISSUE TITLE
interface methods not recognized by trait implementation

### ISSUE THREAD

**Issue by hagnat** [pdt-eg/Core-Plugin#129]
If my class implements an Interface, and uses a Trait to implement the required functions, PDT does not recognize this and keeps asking me to implement those methods.

```php
<?php
interface FooInterface {
    public function doSomething();
}
trait FooTrait {
    public function doSomething() {
        // do something
    }
}
class Foo implements FooInterface {
    use FooTrait;
    public function doSomethingElse() {
    }| auto complete asks me to implement 'doSomething()'
}
```

often, when i am typing too fast, the auto-complete tool will insert a stub implementation of the first function required by the interface that is implemented on the trait

```php
<?php
interface AuditableInterface {
    public function getCreatedAt();
}
trait Auditable {
    public function getCreatedAt() {}
}
class SomeRandomClass implements AuditableInterface {
    use Auditable;

    protected $contactId;|my cursor was here and i quickly typed enter twice
 /* (non-PHPdoc)
  * @see AuditableInterface::getCreatedAt()
  */
 public function getCreatedAt() {
  // TODO: Auto-generated method stub
 }
```

**Comment by hagnat** [comment]
refereed to this project by the eclipse PDT team (see https://bugs.eclipse.org/bugs/show_bug.cgi?id=476985)

**Comment by zulus** [comment]
Second problem (fast typing and ctrl+space), is known bug with wrong context detection: https://bugs.eclipse.org/bugs/show_bug.cgi?id=459947

**Comment by hagnat** [comment]
what about the first problem ?
CA keeps asking me to implement interface methods implemented by the trait

**Comment by zulus** [comment]
It' fixed in current snapshot.

**Comment by hagnat** [comment]
oic, i missed the fix bit
thanks :)

:+1:
