### ISSUE TITLE
Keep lines starting with // untouched?

### ISSUE THREAD

**Issue by pulse00** [pdt-eg/Core-Plugin#13]
In eclipse I can toggle a bunch of loc with cmd+7 (shift+ctrl+7) and eclipse marks all lines with the double-slash comment at the very beginning of the line. Though the formatter indents them. Well, if you untoggle them, they are wrongly indented, because of the indentation happened when the formatter indented them with the comment in front.

I don't have found the setting to avoid this. Is there one? If not, can there be one to address this?

(originally reported by @gossi)

**Comment by zulus** [comment]
Formatter is no longer part of core-plugin.
