### ISSUE TITLE
sort imported classes

### ISSUE THREAD

**Issue by hagnat** [pdt-eg/Core-Plugin#130]
**Current behavior**
If I import a new class, it will include the 'use' statement at the end of the use block.

``` php
<?php
// before
use Foo\Bar;
// after I request Acme\Foobar to be included
use Foo\Baz;
use Acme\Foobar;
```

**Desired behavior**
When i import a new class, it will be included in alphabetical order in the use block

``` php
<?php
// before
use Foo\Bar;
// after I request Acme\Foobar
use Acme\Foobar;
use Foo\Bar;
```

**Considerations**
- If pdt-eg is importing classes for the first time on an unsorted import list, it will sort them before importing the new class.
- sort imported classes by their actual classname, not by their aliases.

**Comment by zulus** [comment]
PDT since 3.6 have built-in organize imports command. I have to investigate possibilities to reuse part of this feature while adding new import.

**Comment by glen-84** [comment]
> If pdt-eg is importing classes for the first time on an unsorted import list, it will sort them before importing the new class.

Please make this optional and off by default, as it will create unnecessary changes in the file.

**Comment by hagnat** [comment]
How is PDT going to insert the use in the right order, if the block isn't sorted ?
anyway, i agree with making this (as a whole) optional and off by default
while I would love to have this behavior in the IDE, some might not have the same feeling about it

**Comment by zulus** [comment]
This task probably should be moved to PDT directly. Use statement injector is part of it.

Sorting could be done as part of save participants (planned PDT feature).

**Comment by glen-84** [comment]
> How is PDT going to insert the use in the right order, if the block isn't sorted ?

Load the current imports into an array, iterate over them while the import-to-be-added is > the current import, and insert the import at that position (i - 1).

e.g. Starting with this:

```php
use A1;
use B2;
use A2;
```

If you wanted to import `C`, it would be added at the end, as it's greater than all existing imports.

If you wanted to import `B1`, it would be added after `A1`, as it's not greater than `B2`.

The alternative is to detect if the imports are already sorted (sort them, compare with unsorted) and then insert at the end if they are not.

**Comment by glen-84** [comment]
> Sorting could be done as part of save participants (planned PDT feature).

I wouldn't use this for the reason mentioned above, so I'd still want the inserted statement to be positioned alphabetically.

Ideally there would be 3 options:

1. Insert at the end.
2. Insert in alphabetical order.
2. Insert in alphabetical order (only when already sorted).

**Comment by hagnat** [comment]
@glen-84 
> If you wanted to import B1, it would be added after A1, as it's not greater than B2.

so it keeps the ```use``` block somehow organized, even if it isn't really sorted
yeah, this is a simple solution which i could compromise with :+1: 

we could have a second command to alphabeticaly sort the use block
@zulus, the built-in command you mentioned before, how does it work ?

**Comment by zulus** [comment]
Built-in PDT Organize Imports command doing two things right now:
1. Remove unused imports (use statements)
2. Reinsert it alphabetically 

You can invoke it via ctrl/cmd+shift+o or ctrl/cmd+1 on unused import.

**Comment by glen-84** [comment]
> 2. Reinsert it alphabetically

This is not ideal. What should be a 1-line change can now be a multi-line change. I think that sorting should be a separate command (or at least configurable).

**Comment by zulus** [comment]
This should be done on PDT side. Closing.

**Comment by glen-84** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=533103
