### ISSUE TITLE
How to exclude folder from semantic analysis?

### ISSUE THREAD

**Issue by glen-84** [pdt-eg/Core-Plugin#131]
I want to exclude the vendor folder, but I don't see the semantic analysis validator on the Validation preferences page:

![validation](https://cloud.githubusercontent.com/assets/261509/10563753/2dccb73c-7597-11e5-8fb7-b1413bc88567.png)

How can I do this?

**Comment by zulus** [comment]
you have two options:

1. If you want disable only SemanticAnalysis, mark vendor as derived. Right click on dir and select Derived attribute
2. If you want disable all validators, right click on folder and "mark as library folder". This is how Composer Plugin disable all validators in vendor.

**Comment by glen-84** [comment]
@zulus Thanks, option 2 was what I needed.
