### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by glen-84** [pdt-eg/Core-Plugin#132]
http://www.pdt-extensions.org/ returns "Server not found" – will this be fixed?

**Comment by zulus** [comment]
@pulse00  ?

**Comment by shakaran** [comment]
This issue should be easy to fix adding a CNAME record in the DNS domain

**Comment by shakaran** [comment]
Still  not fixed:

```
$ dig A www.pdt-extensions.org

; <<>> DiG 9.11.5-P4-5.1ubuntu2.1-Ubuntu <<>> A www.pdt-extensions.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 6621
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;www.pdt-extensions.org.		IN	A

;; Query time: 0 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: vie may 15 04:02:32 CEST 2020
;; MSG SIZE  rcvd: 51

```

**Comment by zulus** [comment]
And never will be. Looks like @pulse00 is no interested to fix that. Also plugin will be removed in near future, last feature will be reimplemented on PDT itself : eclipse/pdt#51

Soon, same will happen with other plugins already managed by me on pdt-extensions.org (Twig / Doctrine / Symfony)
