### ISSUE TITLE
Marking an used variable as unused, take VI

### ISSUE THREAD

**Issue by tbl0605** [pdt-eg/Core-Plugin#135]
Hi,
a new case of variable (wrongly) marked as unused : 

<?php
class MyConf
{
    public static $emails = array(
        'from' => array(
            'myemail@home.com',
            'my name 1'
        ),
        'to' => array(
            'myemail@work.com',
            'my name 2'
        )
    );
}
// Everything is OK :
MyConf::$emails['from'];
// Wrongly marked as unused (and undefined) :
MyConf::$emails['from'][0];

**Comment by tbl0605** [comment]
Hi,
I complete previous test case, as this bug seems a bit more complicated than I thought:

<?php
class MyConf
{
    public static $emails = array(
        'from' => array(
            'myemail@home.com',
            'my name 1'
        ),
        'to' => array(
            'myemail@work.com',
            'my name 2'
        )
    );
}
// Everything *seems* OK, but actually no test was done on "MyConf::$emails['from']" ...
MyConf::$emails['from'];
// ... because following one is also (wrongly) marked as used:
MyConf::$emailsssss['from'];
// Wrongly marked as unused (and undefined):
MyConf::$emails['from'][0];

**Comment by zulus** [comment]
One week ago I released new Core plugin version. It works correctly right now with you example. Can you check again?

**Comment by tbl0605** [comment]
Yes I downloaded latest release, but no it doesn't work.
If I look at the changelog of Core-Plugin, you did lately just a version bump, I see no changes related to my bug report.
I'm using http://p2-dev.pdt-extensions.org/ and http://download.eclipse.org/tools/pdt/updates/latest-nightly

**Comment by zulus** [comment]
OK I see this now. It's related to PDT PHP 5.6 parser. `MyConf::$emails['from'];`  is resolved as:

`StaticFieldAccess(ClassName(MyConf), ArrayAccess(Variable($emails), Index(from)))`

should be:

`ArrayAccess(StaticFieldAccess(ClassName(MyConf, Variable($emails)), index(from))`

**Comment by zulus** [comment]
In PHP7 works fine.

**Comment by zulus** [comment]
PDT bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=489554

**Comment by tbl0605** [comment]
Ok now I understand why it doesn't work for me, I'm not using the PHP 7 parser at work (we're still stuck at PHP 5.4 !) :) I will have a look again when bug 489554 is resolved, thank you ! ;)

**Comment by zulus** [comment]
Patch for bug 489554 merged, so I'm closing this one.

**Comment by tbl0605** [comment]
Thank you @zulus ! :)
