### ISSUE TITLE
Move class / interface wizards to PDT

### ISSUE THREAD

**Issue by zulus** [pdt-eg/Core-Plugin#136]
I think it's time for that. Besides composer migration become easier. https://wiki.eclipse.org/PDT/Composer_Migration

Any objections?

**Comment by tbl0605** [comment]
Great idea ! :) But please don't forget to have a look at  #135 if you have some time in the future ;) Thank you ! :)

**Comment by zulus** [comment]
@pulse00 @Mandos ?

**Comment by Mandos** [comment]
I would like to move it PDT but I will be honest, I don't like this code :), I think it would be better to write it from scratch. I try to look at it in next two weeks.

**Comment by Mandos** [comment]
I would like to move it PDT but I will be honest, I don't like this code :), I think it would be better to write it from scratch. I try to look at it in next two weeks.

**Comment by zulus** [comment]
Any luck?

**Comment by Mandos** [comment]
I will implement it, but I don't have much time so it takes me some time :)

**Comment by zulus** [comment]
Hi, I grab some time for a weekend and can do this. I hope to add this feature into PDT 4.0.

**Comment by zulus** [comment]
I failed :P There was more important bugs.

I want create / move such feature during 4.1 cycle (Neon.1), together with https://bugs.eclipse.org/bugs/show_bug.cgi?id=472758

**Comment by zulus** [comment]
Eclipse bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=501259
Now when Composer support is part of PDT should be easier ;)

**Comment by zulus** [comment]
Rogue Wave Software Inc moving Zend Studio wizards to PDT [1]. After merge I'll close this bug and remove PEX implementation.

[1] - https://git.eclipse.org/r/#/c/92686/
