### ISSUE TITLE
Move builds to a managed CI solution

### ISSUE THREAD

**Issue by pulse00** [pdt-eg/Core-Plugin#142]
I'd like to move the jenkins build away from my private (https://ci.pdt-extensions.org/) server to some hosted jenkins solution. I'll ask https://www.cloudbees.com/ support if they still have a free open-source tier. 

@zulus ok with you?

**Comment by zulus** [comment]
Sure, if something goes wrong I'll prepare instance on one of my servers ;)

**Comment by zulus** [comment]
BTW, can you redirect http://www.pdt-extensions.org/ to http://pdt-extensions.org/ ?

**Comment by zulus** [comment]
I saw new badge for code ship. Do you need help with migration?
