### ISSUE TITLE
Proposal: Show warning when type referenced in docBlock is not valid

### ISSUE THREAD

**Issue by mcustiel** [pdt-eg/Core-Plugin#152]
It would be nice that the semantic analysis shows a warning when a Class referenced in `@var` or `@return` or `@param` is invalid.
For instance:

```
/**
 * @var MyClassName
 */
private $myProperty;
```
Should show a warning if MyClassName is not in the same namespace that the current class and was not included with a `use` statement.

From: https://github.com/pdt-eg/p2-mirror-dev/issues/17

**Comment by zulus** [comment]
This is already implemented in PDT
