### ISSUE TITLE
PHP 7.1 void return type is unknown 

### ISSUE THREAD

**Issue by mniewrzal** [pdt-eg/Core-Plugin#155]
Code:
```php
<?php
class a
{
    public function f(): void
    {
        
    }
}
```
![voidwarn](https://cloud.githubusercontent.com/assets/7313031/26713794/a696ac2c-476e-11e7-8f1f-3ccba13bcc2a.png)

**Comment by zulus** [comment]
PDT have now own validator, Core-Plugin has been removed.
