### ISSUE TITLE
Outline View appears broken for php/js scripts in Neon 

### ISSUE THREAD

**Issue by ajmaske** [pdt-eg/Core-Plugin#156]
Took 4 days of reinstalling over and over to finally narrow this down ...  Outline View for .php and .js scripts appears to be broken.  Happened in one of the last couple releases.

In stock eclipse neon install Outline View works as expected, once I install p2.pdt it breaks.  Outline View is blank for both .php and .js scripts, however seems to work fine with others (ie .html, .css, .java, etc ...)

I opened a bug report with Eclipse (https://bugs.eclipse.org/bugs/show_bug.cgi?id=519123) thinking the problem was with it.

**Comment by zulus** [comment]
Looks likemixed plugin versions. Core-Plugin plug p2.pdt-extensions.org require latest stable PDT, from p2-dev.pdt-extensions.org require often latest nightly build.
