### ISSUE TITLE
"Variable is never used" warning when foreach value assigned by reference

### ISSUE THREAD

**Issue by glen-84** [pdt-eg/Core-Plugin#157]
Code:

```php
foreach ($rankings['data'] as &$ranking) {
    $ranking['type'] = 'team';
}
```

Warning:

`Variable $ranking is never used`

... false positive?

(moved from https://bugs.eclipse.org/bugs/show_bug.cgi?id=529164)

**Comment by zulus** [comment]
Fixed on PDT

**Comment by glen-84** [comment]
@zulus This is still not working in `PHP Development Tools (PDT) 6.0.0.201806122250`.

**Comment by glen-84** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=537262
