### ISSUE TITLE
Allow $v to be unused in foreach ($a as $k => $v) { $k; } (?)

### ISSUE THREAD

**Issue by glen-84** [pdt-eg/Core-Plugin#158]
Code:

```php
foreach ($a as $k => $v) { $k; }
```

Warning:

`Variable $v is never used`

In these cases, `$v` is unused, but it has to be there. The alternative (using `array_keys`) will likely be slower.

Perhaps it should be allowed as long as `$k` is used? *At least* as an option, but TBH I think it could even be the default.

Workaround:

```php
/* @var $v string */
foreach ($a as $k => $v) { $k; }
```

(moved from https://bugs.eclipse.org/bugs/show_bug.cgi?id=529167)

**Comment by zulus** [comment]
I changed my mind and fixed without additional UI switch. I completely forgot about PHP copy-on-write feature.

**Comment by glen-84** [comment]
I have *no* idea what that means. 😆

**Comment by zulus** [comment]
Until first edit, variable behave similar to reference.

**Comment by glen-84** [comment]
I think I understand now. Thanks.
