### ISSUE TITLE
Variable $func is undefined

### ISSUE THREAD

**Issue by DarkNami** [pdt-eg/Core-Plugin#161]
Eclipse IDE for PHP Developers
Version: 2019-09 R (4.13.0)
Build id: 20190917-1200

Variable '$func' is defined but I got "Variable '$func' is undefined" problem.
(Variable defined and used in 'use' immediately.)

```php
public static function findChildrens(array $flatArray, $pidKey, $idKey, $pid) {
	$result = [];
	$func = function ($pid) use (&$func, &$result, $flatArray, $pidKey, $idKey) {
		foreach ($flatArray as $el) {
			if ($el[$pidKey] === $pid) {
				$result[] = $el;
				$func($el[$idKey]);
			}
		}
	};
	$func($pid);
	return $result;
}
```
![圖片](https://user-images.githubusercontent.com/5100919/66388933-c1db1600-e9f9-11e9-8939-5618220e656d.png)

Thank you.

**Comment by zulus** [comment]
Validation is part of PDT. See bug report: https://bugs.eclipse.org/bugs/show_bug.cgi?id=550928

**Comment by DarkNami** [comment]
I understand, thank you.
