### ISSUE TITLE
Space before parenthesis in anonymous functions

### ISSUE THREAD

**Issue by heruan** [pdt-eg/Core-Plugin#35]
I see no option to avoid the space after `function` and `use` keywords in anonymous function declaration, like in:
````
$server->on('request', function ($request) use ($dispatcher) {
  $response = $dispatcher->dispatch($request);
  $this->send($response);
});
````
It would be useful since Formatter adds spaces even if there are none before formatting.

**Comment by zulus** [comment]
Formatter is no longer part of this plugin. Closing.
