### ISSUE TITLE
Getters/setters generation for doc properties

### ISSUE THREAD

**Issue by augusteiner** [pdt-eg/Core-Plugin#39]
The editor already shows the dialog to generate getters/setters of properties in the class/interface doc, but if at least one attribute isn't declared with the same name of the property in doc the getters/setters code is not added.

This could be a nice functionality also, to add getters/setters to interfaces without declaration of attributes (of course it's an interface) using only the properties in the interface doc.

**Comment by zulus** [comment]
Info: Generation for static attributes is already implemented.
