### ISSUE TITLE
PHP Package Explorer View

### ISSUE THREAD

**Issue by iteman** [pdt-eg/Core-Plugin#60]
[PSR-0](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-0.md) compliant view like the **Package Explorer** view.

**Comment by zulus** [comment]
PDT have namespace view in php explorer ("group by namespaces"). Since 3.4 it's also grouped under each build path (like JDT package explorer).

This mode still have some bugs, but I think can be close this one.
