### ISSUE TITLE
Function override forgets to add use statements

### ISSUE THREAD

**Issue by gossi** [pdt-eg/Core-Plugin#67]
I override my `doRun` method from a parent class. This is the signature:
`protected function doRun(Request $request, Response $response, ApplicationRouter $appRouter)`

`Request`, `Response` and `ApplicationRouter` weren't added to the use statement. This involves a manual step.

**Comment by mcustiel** [comment]
+1

**Comment by zulus** [comment]
Support dropped. It's part of PDT 5.0
