### ISSUE TITLE
Classes generator wizard works half

### ISSUE THREAD

**Issue by remizero** [pdt-eg/Core-Plugin#68]
good afternoon, I am writing to congratulate you for this wonderful idea, an excellent initiative for us php developers in eclipse.And tell you that I have noticed that when trying to create a class with the wizard does not display the dialog.

At first I thought the problem was due to the fact of working with multiple workspaces and some of these were damaged, but as more projects I was working on the problem presented to me in all workspaces.

Then I realized trying combinations that generate classes wizard only works with a single project but not charged with several.I hope they can so they can solve that detail, I understand that the extension is still developing and it is understandable that errors may occur.

Cheers and good luck with the project, I am one of your new and from now on, its more user ferreo

**Comment by zulus** [comment]
These dialogs are no longer part of this plugin.
