### ISSUE TITLE
Add "Organize Imports" feature

### ISSUE THREAD

**Issue by pulse00** [pdt-eg/Core-Plugin#8]
In Java editor we have this feature in [<Right click> >] Source > Organize Imports, with the keyboard shortcut Ctrl+Shift+O. PHP editor misses it, and this extension could kindly implements it :p

(Original issue created by @Dentxinho )

**Comment by raziel057** [comment]
+1 for this one. The problem comes from the fact that there is no way to get the full list of import depending on the class instantiation.

For example if I write ``$myObject = new $myClass()`` it's not possible to import the class which must be resolved at runtime.

**Comment by zulus** [comment]
This will be part of PDT 3.6: https://bugs.eclipse.org/bugs/show_bug.cgi?id=354782

Pending patch have both, organize features and unused imports validator.
