### ISSUE TITLE
Some buttons in the "PHP Coding Standard Fixer" preferences panel are nearly inaccessible

### ISSUE THREAD

**Issue by tbl0605** [pdt-eg/Core-Plugin#88]
See the attached screenshot, some buttons in the preferences panel are nearly inaccessible.

![cs fixer](https://cloud.githubusercontent.com/assets/3315731/2601218/7e972586-bb0c-11e3-8d37-1ec02cd9d87b.jpg)

**Comment by macik** [comment]
+1 for this issue.

More over getting these errors for Preferences window:
```
preference option missing: org.pdtextensions.semanticanalysis/org.pdtextensions.semanticanalysisuse_project_phar (org.pdtextensions.semanticanalysis.ui.preferences.csfixer.PHPCSFixerConfigurationBlock)
```

![2015-09-18_21-46_event details](https://cloud.githubusercontent.com/assets/1009926/9968105/3e2629b0-5e4f-11e5-885f-fe3aa4f5fc0e.png)

**Comment by zulus** [comment]
I'm unable to reproduce on windows 10. Is this problem with windows 7 only?

**Comment by macik** [comment]
I'm using Win7x64 with large fonts setting: Control panel → Display → Medium fotn size (125%)

I don't know is there any settings for system font in Windows10, but I think it can be source of a problem:

Here how it looks like on my PC

![2015-09-20_13-58_preferences](https://cloud.githubusercontent.com/assets/1009926/9980432/548d3c30-5fa2-11e5-8d41-0245a6a5613c.png)

**Comment by zulus** [comment]
Still no luck, I have to find my old VM with win7...
